### ISSUE TITLE
Remove winmail.dat preference removes additional attachments

### ISSUE THREAD

**Issue by dugite-code** [TB-throwback/LookOut-fix-version#106]
The `Remove Winmail.dat` preference in the webextension re-architecture causes additional attachments such as forwarded emails to be removed as well.

It is questionable if this is the wrong behavior or not as Microsoft emails do not send additional attachments or not. It may be advisable to keep additional attachments in a future version update.

**Comment by jobisoft** [comment]
Could you release v6.1 with this fix?

**Comment by dugite-code** [comment]
Yep, I was hoping to be able to get #35 done along side but had some other thing come up.
