### ISSUE TITLE
Thunderbird (supernova) 115.3.1 seems to have broken LookOut-fix extension

### ISSUE THREAD

**Issue by nckramer** [TB-throwback/LookOut-fix-version#108]
Thunderbird (supernova) 115.3.1 seems to have broken LookOut-fix extension

* Operating System: macOS Monterey 12.6.8
* Thunderbird version number: Supernova 115.3.1 (64-bit)
* LookOut (fix version) version number: 6.1

updated to the latest version of thunderbird "supernova' 115.3.1 and seems to have broken the extension.
- trying to save the files either individually or "save all", nothing gets saved.
- turning the extension off i can get it to save the original windmain.dat file.

i know this is an older extension and not sure if there are plans for an update, but would be greatly appreciated. 

i've searched around and this is the only one i can find that can handle incoming windmail files.

i can run tests if needed or test/feedback of new update, if you'd like.

thanks again for all your efforts.
this extension makes life a lot easier for clients who are a little technology challenged.

**Comment by dugite-code** [comment]
Duplicate: https://github.com/TB-throwback/LookOut-fix-version/issues/105

We are currently awaiting upstream work. To save files you'll have to click, hold, drag and drop the files visually.

**Comment by dugite-code** [comment]
Oh you can also right click and select `open the containing folder` to access the files.

![image](https://github.com/TB-throwback/LookOut-fix-version/assets/12742064/ebd1fada-b31f-4c1f-a1dc-3afeef351dac)
