### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by topoldo** [TB-throwback/LookOut-fix-version#113]
Hi.
This is NOT a bug report; it is the proposal to have me as the Italian translator of this extension.
So, herein you find attached the Italian "message.json"
It is not fully translated because I suppose that some strings ie:

```
"extensions.lookout.attach_raw_mapi": {
        "message": "false"
    }

    "extensions.lookout.body_part_prefix": {
        "message": "body_part_"
    }

    "extensions.lookout.direct_to_calendar": {
        "message": "false"
    }
    
"extensions.lookout.disable_filename_character_set": {
        "message": "false"
    }

```
should not be translated.
Please tell me if I was wrong.

Regards,
Leopoldo aka Topoldo

[messages.json](https://github.com/TB-throwback/LookOut-fix-version/files/14314826/messages.json)

**Comment by dugite-code** [comment]
Hi thanks for offering translation help. It's better to submit a pull request to have your changes included. Otherwise it will only be included eventually™ when I have time. 

All strings can be translated, the only limiting factor is the body_part_prefix shouldn't have any spaces.

**Comment by dugite-code** [comment]
Yes, you fork, create a new branch (or patch but branch is easiest) push your changes to said branch and then create a pull request.

https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/
