### ISSUE TITLE
Saving attachments in winmail.dat does not work (64 bit TB 115.12.2 esr, Windows 10, 64bit)

### ISSUE THREAD

**Issue by andras63** [TB-throwback/LookOut-fix-version#117]
I can click and open individual pdfs out of the decoded Winmail.dat, but saving is not possible (seems to work - no message - but saves nothing)

**Comment by andras63** [comment]
Note that file names contain spaces...
Example:
![Attachments](https://github.com/TB-throwback/LookOut-fix-version/assets/42473862/9819fa2f-8962-4ae9-8aa8-bf4353a47dfc)

**Comment by dugite-code** [comment]
Duplicate https://github.com/TB-throwback/LookOut-fix-version/issues/105

The current work-around until an upstream change is implemented:
> Users currently must drag and drop files or open the containing folder to access files.
