### ISSUE TITLE
Not compatible with Thunderbird 128

### ISSUE THREAD

**Issue by JP95Git** [TB-throwback/LookOut-fix-version#118]
## Context

* Operating System: Windows 10
* Thunderbird version number: 128esr
* 64 bit/32 bit: 64 Bit
* LookOut (fix version) version number: 6.2 (not working)

# Expected Behavior

LookOut (fix version) works in Thunderbird 128.

# Current Behavior

LookOut (fix version) does not in Thunderbird 128.

## Steps to Reproduce

Upgrade Thunderbird to version 128. Bug surprise: Most of the addons (including LookOut) no longer works.

**Comment by jobisoft** [comment]
> Bug surprise: Most of the addons (including LookOut) no longer works.

70% of the top 40 addons are compatible. In total 76 addons of all thunderbird addons are not yet compatible. It would help if these vast exaggeration would stop. It does not help anyone. Most addon developers start working on the updates after initial release of the new ESR which was a few days ago. Give them some time!

**Comment by JP95Git** [comment]
Sorry if my text was misunderstood. I wanted to say that the majority of **my** addons do not work with Thunderbird 128. To be more precise, all but one rarely used adddon are currently not working.

**Comment by jobisoft** [comment]
Pull request for compatibility with Thunderbird 128 provided in https://github.com/TB-throwback/LookOut-fix-version/pull/119

**Comment by dugite-code** [comment]
Thanks as always @jobisoft new version uploaded. I'm hoping I can start scrounging some more free time to keep on top of this again.
