### ISSUE TITLE
Thunderbird Beta 60+ hangs due winmail.dat

### ISSUE THREAD

**Issue by petesky** [TB-throwback/LookOut-fix-version#17]
On IMAP inbox i setup read only mail headers. While enabling LookOut thunderbird becomes completely unusable just when selecting a mail with winmail.dat attachment and i have to kill the tb process. Repaired msf folder as described does not help.

**Comment by dugite-code** [comment]
1. could you please enable debugging and check the error console for logs.

![image](https://user-images.githubusercontent.com/12742064/46715081-091cb280-cc91-11e8-9c59-05a77a3b1a40.png)

  2. If at all possible submitting a sample winmail.dat file would be of help

**Comment by dugite-code** [comment]
Also Please list your settings:

Mine are:
- [ ] Attach MAPI Properties
- [x] Open Calendaring Data Directly
- [ ] Disable Filename Character Set Conversion
- [x] Strict Content Type Matching
- [x] Enable Debugging

**Comment by dugite-code** [comment]
From my experience it is unlikely to be the email itself rather it would most likely be an error in the parsing of the .dat file

The alternative to the debug dialogue is to open the Debug toolbox (, This splits off as a separate process and shouldn't crash with Thunderbird.

![image](https://user-images.githubusercontent.com/12742064/46724036-c3b9ae80-ccab-11e8-8097-74a9e28a77ae.png)

![image](https://user-images.githubusercontent.com/12742064/46724077-d9c76f00-ccab-11e8-8707-9c6d593b1bec.png)

![image](https://user-images.githubusercontent.com/12742064/46724205-1c894700-ccac-11e8-92dc-880b3d97ae3a.png)


Unfortunately from these scant details I can not help you to resolve this issue.

**Comment by petesky** [comment]
There is no additional entry in debugging tools JS exception as well. TB writes "loading message ..." and is not responding at all.

**Comment by petesky** [comment]
For privacy reason i only can provide the mail content simplified but maybe the encoded part is the problem ?

```
X-Mozilla-Status: 1001
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
Content-Type: multipart/mixed;
	boundary="_000_000000000000000000000000000000000000000000000000xxxxxxx_"
X-MS-Has-Attach:
X-MS-TNEF-Correlator: <0000000000000000000000000000000000000000@00000000.xxx.xxxxxx>
MIME-Version: 1.0

--_000_000000000000000000000000000000000000000000000000xxxxxxx_
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Test

--_000_000000000000000000000000000000000000000000000000xxxxxxx_
Content-Disposition: attachment; filename="winmail.dat"
Content-Transfer-Encoding: base64
Content-Type: application/ms-tnef; name="winmail.dat"

Here ist the encoded part

--_000_000000000000000000000000000000000000000000000000xxxxxxx_--


```

**Comment by dugite-code** [comment]
1. I don't see the `loading message ...` when viewing the debug logs. What other add-ons do you have installed? I do remember seeing some reports of incompatibility with Thunderbird Conversations. although I haven't looked into it personally

   2. I'm assuming you modified `--_000_000000000000000000000000000000000000000000000000xxxxxxx_--` for your post? Otherwise it doesn't look incorrect and is rather typical of tnef emails the only difference with the samples I have is the `charset="iso-8859-1"` but thunderbird handles that and shouldn't cause any problems

**Comment by petesky** [comment]
I have only enigmail with auto setting and yes i modified the header including the boundary for privacy reason (sorry, removed ip,from,to, subject etc). If headers and mail structure is not the problem, i assume m$ is encoding the content TNEF not in proper way. I only read subject from IMAP and decide which mail to download or delete. Another option can be a problem with TB itself or junk filter or ... ? So thank you for investigating so far - i will do my best to debug this issue next time it happens.

**Comment by dugite-code** [comment]
No worries, it could be because of the age of the Lookout parser, it's not seen an update since the original author back in 2011.

I'm looking at integrating a newer parser at some point so try to keep a hold of that email.

**Comment by andyboeh** [comment]
I'm affected by the same problem, but I get a timeout in tnef.js:1265 after a while.

**Comment by andyboeh** [comment]
I did get debug entries, here is the trace (edited a bit for privacy):
```
LookOut: debug enabled 
LookOut: Entering on_end_all_attachments()
LookOut: Entering scan_for_tnef()
({contentType:"application/ms-tnef", name:"winmail.dat", uri:"imap-message://xxxxxxxxxxxxxxxxxxxxxxxxxx", isExternalAttachment:false, size:9080, partID:"1.2", url:"imap://xxxxxxxxxxxxxxxxxxxxxxxxxxxx?part=1.2&filename=winmail.dat"})
LookOut:    Content Type: 'application/ms-tnef'
LookOut:    found tnef
LookOut: Entering onDataAvailable()
TNEF: Entering tnef_pack_parse_stream()
TNEF Key: 3e0c
checksum = 1  sum = 1
checksum = 232  sum = 232
TNEF: OEM Code Page = 1252
checksum = 1949  sum = 1949
checksum = 2  sum = 2
checksum = 310  sum = 310checksum = 2903  sum = 2903
checksum = 3226  sum = 3226
checksum = 269  sum = 269
checksum = 271  sum = 271
checksum = 8821  sum = 8821
Error: Script terminated by timeout at:
decompose_rfc822_address@chrome://lookout/content/tnef.js:1265:15
tnef_pack_get_name_addr@chrome://lookout/content/tnef.js:1281:25
tnef_pack_appt_attendees_ics@chrome://lookout/content/tnef.js:1553:17
tnef_pack_handle_appt_data@chrome://lookout/content/tnef.js:1642:17
tnef_pack_parse_stream@chrome://lookout/content/tnef.js:1866:6
onDataAvailable@chrome://lookout/content/lookout.js:338:19
  tnef.js:1265:15
LookOut: Entering onStopRequest()
```

**Comment by dugite-code** [comment]
Unfortunately I'm not 100% sure what's causing the issue, I dare say it's in the ICS parsing where sometimes it pops out an illegal character see: https://github.com/TB-throwback/LookOut-fix-version/issues/27#issuecomment-445091173

**Comment by dugite-code** [comment]
@andyboeh [Beta Release v1.2.25b1](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.2.25b1) has multiple changes and might catch that issue if we are lucky. If you can test them it would be appreciated.

**Comment by andyboeh** [comment]
Sorry, I wasn't subscribed to the issue or I overlooked the notification. Anyhow, I tested 1.2.25b1 just now, unfortunately, it doesn't fix the issue.

**Comment by NicolasGoeddel** [comment]
We go the same issue here. Our whole company uses Thunderbird but some of our customers send us mails using Outlook with invitations and things. We then get these horrible winmail.dat files and our Thunderbird freezes when we click on such mails. But it does not happen every time.
I can't understand why this crap still exists. Can I help here in any way? I also can not send you example mails containing sensible information but maybe I can craft an email especially for you to find and fix that nasty bug. :-) 

btw.: Burn Outlook! Burn!

**Comment by dugite-code** [comment]
@NicolasGoeddel if you could provide some details about your system and debug logs that would be helpful. Also did you try the beta release? [Beta Release v1.2.25b1](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.2.25b1) I've found it's generally the invitations that cause these issues and I made some changes to try address that in the beta. I didn't issue a release as this didn't address all these issues.

* Operating System:
* Thunderbird version number:
* 64 bit/32 bit:
* LookOut (fix version) version number:

If you are able to get an non-sensitive email that has similar issues please send it (as an attachment or full redirect) to lookout@peekread.info and I'll try have a look into it.

**Comment by NicolasGoeddel** [comment]
The Beta Release seems not to help here. There is still a freeze when I try to open certain mails.

I will try to craft a mail without sensitive information.

For the beginning here is the output of the debugger after a timeout:
```
DebuggeeWouldRun: debuggee `resource://devtools/shared/base-loader.js:428' would run  builtin-modules.js:185:11
GetPrettiestName is deprecated and will be removed soon.  (unbekannt)
Error: Script terminated by timeout at:
decompose_rfc822_address@chrome://lookout/content/tnef.js:1265:15
tnef_pack_get_name_addr@chrome://lookout/content/tnef.js:1281:25
tnef_pack_appt_attendees_ics@chrome://lookout/content/tnef.js:1553:17
tnef_pack_handle_appt_data@chrome://lookout/content/tnef.js:1639:17
tnef_pack_parse_stream@chrome://lookout/content/tnef.js:1870:6
onDataAvailable@chrome://lookout/content/lookout.js:310:19
  tnef.js:1265:15
TypeError: this._parentMenupopup is null[Weitere Informationen]  mailWidgets.xml:2733:9
	splitmenu_XBL_Destructor chrome://messenger/content/mailWidgets.xml:2733:9
	_setupAppmenu chrome://messenger/content/mailWidgets.xml:2835:17
	onxblmousedown chrome://messenger/content/mailWidgets.xml:2851:1
Error: Script terminated by timeout at:
decompose_rfc822_address@chrome://lookout/content/tnef.js:1265:15
tnef_pack_get_name_addr@chrome://lookout/content/tnef.js:1281:25
tnef_pack_appt_attendees_ics@chrome://lookout/content/tnef.js:1553:17
tnef_pack_handle_appt_data@chrome://lookout/content/tnef.js:1639:17
tnef_pack_parse_stream@chrome://lookout/content/tnef.js:1870:6
onDataAvailable@chrome://lookout/content/lookout.js:310:19
  tnef.js:1265:15
GetPrettiestName is deprecated and will be removed soon.  (unbekannt)
uncaught exception: 2147746065  autosync.js:206:13
DebuggeeWouldRun: debuggee `resource://devtools/shared/base-loader.js:428' would run  builtin-modules.js:185:11
"Failed to enumerate localStorage for host chrome:/content/messenger.xul: [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js :: populateStoresForHost :: line 1158"  data: no]"  storage.js:1160:9
"Failed to enumerate localStorage for host chrome:/content/msgAccountCentral.xul: [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js :: populateStoresForHost :: line 1158"  data: no]"  storage.js:1160:9
"Failed to enumerate localStorage for host about:addons: [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js :: populateStoresForHost :: line 1158"  data: no]"  storage.js:1160:9
"Failed to enumerate sessionStorage for host chrome:/content/messenger.xul: [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js :: populateStoresForHost :: line 1158"  data: no]"  storage.js:1160:9
"Failed to enumerate sessionStorage for host chrome:/content/msgAccountCentral.xul: [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js :: populateStoresForHost :: line 1158"  data: no]"  storage.js:1160:9
"Failed to enumerate sessionStorage for host about:addons: [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js :: populateStoresForHost :: line 1158"  data: no]"  storage.js:1160:9
[object InvisibleToDebugger: Error]  protocol.js:964:5
	writeError resource://devtools/shared/protocol.js:964:5
	handler/</< resource://devtools/shared/protocol.js:1143:31
	process resource://gre/modules/Promise-backend.js:928:23
	walkerLoop resource://gre/modules/Promise-backend.js:812:7
	scheduleWalkerLoop/< resource://gre/modules/Promise-backend.js:748:11
	openModalWindow jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:353:5
	openPrompt jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:563:9
	confirmEx jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:704:9
	decompose_rfc822_address chrome://lookout/content/tnef.js:1265:15
	tnef_pack_get_name_addr chrome://lookout/content/tnef.js:1281:25
	tnef_pack_appt_attendees_ics chrome://lookout/content/tnef.js:1553:17
	tnef_pack_handle_appt_data chrome://lookout/content/tnef.js:1639:17
	tnef_pack_parse_stream chrome://lookout/content/tnef.js:1870:6
	onDataAvailable chrome://lookout/content/lookout.js:310:19
"stylesheets actor: fetch failed for chrome://lookout/skin/overlay.css, using system principal instead."  stylesheets.js:437:7
	fetchStylesheet resource://devtools/server/actors/stylesheets.js:437:7
	openModalWindow jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:353:5
	openPrompt jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:563:9
	confirmEx jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:704:9
	decompose_rfc822_address chrome://lookout/content/tnef.js:1265:15
	tnef_pack_get_name_addr chrome://lookout/content/tnef.js:1281:25
	tnef_pack_appt_attendees_ics chrome://lookout/content/tnef.js:1553:17
	tnef_pack_handle_appt_data chrome://lookout/content/tnef.js:1639:17
	tnef_pack_parse_stream chrome://lookout/content/tnef.js:1870:6
	onDataAvailable chrome://lookout/content/lookout.js:310:19
[object InvisibleToDebugger: Exception]  protocol.js:964:5
	writeError resource://devtools/shared/protocol.js:964:5
	process resource://gre/modules/Promise-backend.js:931:21
	walkerLoop resource://gre/modules/Promise-backend.js:812:7
	scheduleWalkerLoop/< resource://gre/modules/Promise-backend.js:748:11
	openModalWindow jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:353:5
	openPrompt jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:563:9
	confirmEx jar:file:///usr/lib/thunderbird/omni.ja!/components/nsPrompter.js:704:9
	decompose_rfc822_address chrome://lookout/content/tnef.js:1265:15
	tnef_pack_get_name_addr chrome://lookout/content/tnef.js:1281:25
	tnef_pack_appt_attendees_ics chrome://lookout/content/tnef.js:1553:17
	tnef_pack_handle_appt_data chrome://lookout/content/tnef.js:1639:17
	tnef_pack_parse_stream chrome://lookout/content/tnef.js:1870:6
	onDataAvailable chrome://lookout/content/lookout.js:310:19
uncaught exception: 2147746065  autosync.js:206:13
Error: Script terminated by timeout at:
decompose_rfc822_address@chrome://lookout/content/tnef.js:1265:15
tnef_pack_get_name_addr@chrome://lookout/content/tnef.js:1281:25
tnef_pack_appt_attendees_ics@chrome://lookout/content/tnef.js:1553:17
tnef_pack_handle_appt_data@chrome://lookout/content/tnef.js:1639:17
tnef_pack_parse_stream@chrome://lookout/content/tnef.js:1870:6
onDataAvailable@chrome://lookout/content/lookout.js:310:19
  tnef.js:1265:15

```

**Comment by NicolasGoeddel** [comment]
After many tries I was not able to craft a mail with an invitation that triggers the error.
Because the error happens in the function function `decompose_rfc822_address( address )` it would be nice to see somewhere what the value of that `address` variable is. Is it possible to log that address to the error console before calling the `match` method? Maybe that string is enough to debug the issue.

**Comment by NicolasGoeddel** [comment]
As it turns out it was really simple to add a `console.log()` before the `match` line. And this is the simplest way to trigger the timeout using the developer console:
```
company = "Satzweiss.com Print, Web, Software GmbH, Firma (SATZWEISS.COM PRINT, WEB, SOFTWARE GMBH)"
company.match( /^\s*((?:[^\x28\x29\x3c\x3e\x40\x3a\x3b\x5b\x5c\x5d]+|\x22[^\x22]*\x22)*)[\x3c\x28]([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6})[\x29\x3e]\s*$/i );
```
The issue reminds me of this regex freeze issue: https://stackoverflow.com/questions/27782959/js-regex-freezes-my-browsers
Maybe it can help you to fix it.

**Comment by dugite-code** [comment]
Ah good catch, It is definitely that regex that's causing the issue. Unfortunately I'm struggling to find a good alternative to that regex mainly because I don't have enough windat samples to work on.

That said I've added a quick check for `@` symbols to skip the regex entirely as it only appears to hang on complex strings like the one you posted and this may fix your issue. Could you check the new [Beta release v1.2.25b2](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.2.25b2)

**Comment by NicolasGoeddel** [comment]
It seems to work without problems so far. I was able to open many mails which caused thunderbird to freeze in the past.

**Comment by dugite-code** [comment]
@andyboeh, @petesky could you also test the beta release? [Beta release v1.2.25b2](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.2.25b2)

**Comment by andyboeh** [comment]
It doesn't crash anymore - thanks, that's a huge progress! I can see the body_part_0.ics and body_part_1.vcf files. However, the message window, which usually contains a summary of the event and allows me to accept/decline the update, is blank.

**Comment by dugite-code** [comment]
The calendar accept/decline display should be handled with adding attachments inline https://github.com/TB-throwback/LookOut-fix-version/issues/15
