### ISSUE TITLE
Add auto filename character set detection

### ISSUE THREAD

**Issue by parapente** [TB-throwback/LookOut-fix-version#18]
* Operating System: Linux, Windows
* Thunderbird version number: 60.0, 60.2.1
* 64 bit/32 bit: 64bit
* LookOut (fix version) version number: 1.2.22

I attach a screenshot of the filenames as they appear in thunderbird and also the output that ktnef gives when opening the winmail.dat file. You can find the said winmail.dat in the second attachment.

![screenshot_20181016_203748](https://user-images.githubusercontent.com/546860/47035751-72b22a80-d183-11e8-87b3-0afaeb2bed92.png)

[winmail.zip](https://github.com/dugite-code/LookOut-fix-version/files/2484286/winmail.zip)

**Comment by dugite-code** [comment]
@parapente Please go into the add-on settings and check the `Disable Filename Character Set Conversion` option. I Think adding auto character set detection might be possible but I will need to research it.

![image](https://user-images.githubusercontent.com/12742064/47057076-c3606c80-d1f1-11e8-9a02-2044c798d5cf.png)

![image](https://user-images.githubusercontent.com/12742064/47057105-ec80fd00-d1f1-11e8-93db-17798f357879.png)

**Comment by parapente** [comment]
Indeed disabling filename character set conversion works. Thanks! Are the filenames already encoded in a greek character set and they are reencoded? I wouldn't mind having a look at the code but I don't really know the way addons work in thunderbird.
