### ISSUE TITLE
Thunderbird Beta 63

### ISSUE THREAD

**Issue by JFDionne** [TB-throwback/LookOut-fix-version#19]
Hi, any plan to support this version of Thunderbird?

**Comment by dugite-code** [comment]
Eventually, however not in the short term. There are **major** changes with how add-ons work in 63 so it will involve a re-work of the code

**Comment by dugite-code** [comment]
# Notes
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Developing_WebExtensions_for_Thunderbird
