### ISSUE TITLE
ATN links

### ISSUE THREAD

**Issue by ovari** [TB-throwback/LookOut-fix-version#26]
On the [ATN LookOut](https://addons.thunderbird.net/addon/lookout-fix-version/) page, only the “Support site” link is shown.

Suggest updating and adding the following links:
* [Add-on home page](https://github.com/dugite-code/LookOut-fix-version/)
* [Support site](https://github.com/dugite-code/LookOut-fix-version/issues/)
* Support E-mail

For example, [ATN CardBook](https://addons.thunderbird.net/addon/cardbook/) shows these link like
![image](https://user-images.githubusercontent.com/17465872/49058361-c3737380-f257-11e8-8725-a88b0e975bd3.png)

What do you think?

Thank you

**Comment by dugite-code** [comment]
I have used this as an opportunity to transfer the repo to an organisation rather than my personal page.

I have updated the Links as suggested. However I haven't added and email contact. I would prefer people to come here to find solutions/report bugs rather than having multiple locations.
