### ISSUE TITLE
60.6.1 (32 bits) incompatible?

### ISSUE THREAD

**Issue by blurredveg** [TB-throwback/LookOut-fix-version#31]
Hi,
I'm running Thunderbird 60.6.1 (32 bits) and although LookOut-fix-version doesn't claim an incompatibility it no longer seems to function after the latest Thunderbird update.  I'm running on Windows 7 with LookOut (fix version) 1.2.24 - no bug to report, simply that Thunderbird thinks LookOut is installed fine, but I'm seeing winmail.dat etc files again instead of the decoded versions.  It was working fine a few weeks ago (Thunderbird auto-updates on this work machine so I'm afraid I can't give information on when it did a Thunderbird upgrade and from what version).
Thanks for any help!
Chris

**Comment by dugite-code** [comment]
I'm using 60.7.0 (32-bit) on Windows 10 and am seeing no issues.

- Did you enable debugging in the lookout properties dialog 
- Did you restart with all other addons disabled?
- Lookout is incomparable with the [conversations](https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/) plugin, are you using that?
