### ISSUE TITLE
Is winmail.dat still supposed to be listed in the attachments?

### ISSUE THREAD

**Issue by JaredRymer** [TB-throwback/LookOut-fix-version#34]
# Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Context

* Operating System: KDE Neon 18.04
* Thunderbird version number: 60.7.2
* 64 bit/32 bit: 64-bit Tbird / 64-bit OS
* LookOut (fix version) version number: 1.2.25

I asked a co-worker to try it on his Windows PC, same issue.

# Expected Behavior

When you open an email with a winmail.dat attachment Thunderbird would **not** show you the winmail.dat file. But instead just show the actual desired attachment. In this case, just image001.jpg.

# Current Behavior

When you view the email with the attached winmail.dat file it will show the _actual_ expected file (image001.jpg) and the winmail.dat file(s). This makes most people think that the winmail.dat attachment wasn't "decoded" properly. Even though it is. It just shows you everything, which is probably not desired for most people.

A picture is worth a thousand words...
https://i.imgur.com/RFmjcSg.png

## Steps to Reproduce

1. Open email that has a winmail.dat attachment
2. Look at the list of attachments. The winmail.dat file is still there, along with the "decoded" attachment.

# Failure Information (for bugs)

I don't think this is a bug as much as a feature-request. 

Let me know if I missed anything!

**Comment by dugite-code** [comment]
This is the current expected behavior but I do agree this is unnecessarily confusing.

Please test the latest [beta release v1.3.00b1](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.3.00b1) as I have added this as an option. I still need to set it to remain attached if an error occurs but like debugging this is now a checkbox away

**Comment by JaredRymer** [comment]
Thanks for the quick turn around!

I removed the old add-on. Restarted Thunderbird.

Loaded the lookout_fix_version-1.3.00b1-sm+tb.xpi file manually into Thunderbird. Then restarted Thunderbird again.

I changed the options to remove the winmail.dat file. Which it did... but the related files (for me: body_part_0.html and body_part_1.vcf) were not removed. Could this be done as well?

Here are some pictures.
https://i.imgur.com/cwlhbyt.png
https://i.imgur.com/9oAsNb2.png

As a side note, I think the preferences box is cut off at the bottom due to a theming issue. I don't think that's the add-on doing that...

Here is some output. In case you are wanting to see it:

LookOut: debug enabled 
LookOut: Entering on_end_all_attachments()
LookOut: Entering scan_for_tnef()
({contentType:"application/ms-tnef", name:"winmail.dat", uri:"imap-message://johndoe@mail.example.com/INBOX#AnotherUID", isExternalAttachment:false, size:25945, partID:"1.2", url:"imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat"})
LookOut:    Content Type: 'application/ms-tnef'
LookOut:    found tnef
LookOut: Entering onDataAvailable()
TNEF: Entering tnef_pack_parse_stream()
TNEF Key: 276e
checksum = 1  sum = 1
checksum = 232  sum = 232
TNEF: OEM Code Page = 1252
checksum = 1881  sum = 1881
checksum = 2  sum = 2
checksum = 312  sum = 312checksum = 2097  sum = 2097
checksum = 1082  sum = 1082
checksum = 0  sum = 0checksum = 46974  sum = 46974
TNEF: Entering tnef_file_notify()
TNEF: Notifying listener of body_part_0.html, pos = 0, has data = true, is final = true
LookOut: Entering onTnefStart()
LookOut:    adding attachment: imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.1
LookOut: Entering add_sub_attachment_to_list()
LookOut:   content_type:text/html
         atturl:imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.1
         display_name:body_part_0.html
         msguri:imap-message://johndoe@mail.example.com/INBOX#AnotherUID
LookOut:    found new type object: AttachmentInfo ~ Thunderbird 7
LookOut:    registered own function for attachment.open
LookOut:    registered own function for attachment.save
({contentType:"text/html", name:"body_part_0.html", uri:"imap-message://johndoe@mail.example.com/INBOX#AnotherUID", isExternalAttachment:true, size:9490, partID:"1.2", url:"imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.1", lo_orig_open:(function AttachmentInfo_open()
  {
    if (!this.hasFile)
      return;

    if (this.isEmpty) {
      var prompt = document.getElementById("bundle_messenger")
                           .getString("emptyAttachment");
      msgWindow.promptDialog.alert(null, prompt);
    } else {
      messenger.openAttachment(this.contentType, this.url,
                               encodeURIComponent(this.name),
                               this.uri, this.isExternalAttachment);
    }
  }), open:(function () {

				lookout_lib.open_attachment( this );

			}), lo_orig_save:(function AttachmentInfo_save()
  {
    messenger.saveAttachment(this.contentType, this.url,
                             encodeURIComponent(this.name),
                             this.uri, this.isExternalAttachment);
  }), save:(function (save_dir) {

				lookout_lib.save_attachment( this, save_dir );

			}), parent:{contentType:"application/ms-tnef", name:"winmail.dat", uri:"imap-message://johndoe@mail.example.com/INBOX#AnotherUID", isExternalAttachment:false, size:25945, partID:"1.2", url:"imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat"}, part_id:1})
Lookout: Entering redraw_attachment_view()
LookOut:    Parent: [object Object]
            mMsgUri: imap-message://johndoe@mail.example.com/INBOX#AnotherUID
            requested Part_ID: 0
            Part_ID: 1
            Displayname: body_part_0.html
            Content-Type: text/html
            Length: 9490
            URL: 
            mimeurl: imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.1
LookOut: onTnefData position 0  data.len 9490  outstrm null
LookOut: Entering onTnefEnd()
Lookout: Entering redraw_attachment_view()
TNEF: Entering tnef_file_notify()
TNEF: Notifying listener of body_part_1.vcf, pos = 0, has data = true, is final = true
LookOut: Entering onTnefStart()
LookOut:    adding attachment: imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.2
LookOut: Entering add_sub_attachment_to_list()
LookOut:   content_type:text/x-vcard
         atturl:imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.2
         display_name:body_part_1.vcf
         msguri:imap-message://johndoe@mail.example.com/INBOX#AnotherUID
LookOut:    found new type object: AttachmentInfo ~ Thunderbird 7
LookOut:    registered own function for attachment.open
LookOut:    registered own function for attachment.save
({contentType:"text/x-vcard", name:"body_part_1.vcf", uri:"imap-message://johndoe@mail.example.com/INBOX#AnotherUID", isExternalAttachment:true, size:70, partID:"1.2", url:"imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.2", lo_orig_open:(function AttachmentInfo_open()
  {
    if (!this.hasFile)
      return;

    if (this.isEmpty) {
      var prompt = document.getElementById("bundle_messenger")
                           .getString("emptyAttachment");
      msgWindow.promptDialog.alert(null, prompt);
    } else {
      messenger.openAttachment(this.contentType, this.url,
                               encodeURIComponent(this.name),
                               this.uri, this.isExternalAttachment);
    }
  }), open:(function () {

				lookout_lib.open_attachment( this );

			}), lo_orig_save:(function AttachmentInfo_save()
  {
    messenger.saveAttachment(this.contentType, this.url,
                             encodeURIComponent(this.name),
                             this.uri, this.isExternalAttachment);
  }), save:(function (save_dir) {

				lookout_lib.save_attachment( this, save_dir );

			}), parent:{contentType:"application/ms-tnef", name:"winmail.dat", uri:"imap-message://johndoe@mail.example.com/INBOX#AnotherUID", isExternalAttachment:false, size:25945, partID:"1.2", url:"imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat"}, part_id:2})
Lookout: Entering redraw_attachment_view()
LookOut:    Parent: [object Object]
            mMsgUri: imap-message://johndoe@mail.example.com/INBOX#AnotherUID
            requested Part_ID: 0
            Part_ID: 2
            Displayname: body_part_1.vcf
            Content-Type: text/x-vcard
            Length: 70
            URL: 
            mimeurl: imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.2
LookOut: onTnefData position 0  data.len 70  outstrm null
LookOut: Entering onTnefEnd()
Lookout: Entering redraw_attachment_view()
checksum = 1085  sum = 1085
starting file sub-attachment
checksum = 1027  sum = 1027
Lookout: convert file name from charset: WINDOWS-1252
checksum = 345  sum = 345
checksum = 347  sum = 347
checksum = 2705  sum = 2705
checksum = 15281  sum = 15281
Lookout: convert file name from charset: WINDOWS-1252
TNEF: Entering tnef_file_notify()
TNEF: Notifying listener of image001.jpg, pos = 0, has data = true, is final = true
LookOut: Entering onTnefStart()
LookOut:    adding attachment: imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.3
LookOut: Entering add_sub_attachment_to_list()
LookOut:   content_type:image/jpeg
         atturl:imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.3
         display_name:image001.jpg
         msguri:imap-message://johndoe@mail.example.com/INBOX#AnotherUID
LookOut:    found new type object: AttachmentInfo ~ Thunderbird 7
LookOut:    registered own function for attachment.open
LookOut:    registered own function for attachment.save
({contentType:"image/jpeg", name:"image001.jpg", uri:"imap-message://johndoe@mail.example.com/INBOX#AnotherUID", isExternalAttachment:true, size:4702, partID:"1.2", url:"imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.3", lo_orig_open:(function AttachmentInfo_open()
  {
    if (!this.hasFile)
      return;

    if (this.isEmpty) {
      var prompt = document.getElementById("bundle_messenger")
                           .getString("emptyAttachment");
      msgWindow.promptDialog.alert(null, prompt);
    } else {
      messenger.openAttachment(this.contentType, this.url,
                               encodeURIComponent(this.name),
                               this.uri, this.isExternalAttachment);
    }
  }), open:(function () {

				lookout_lib.open_attachment( this );

			}), lo_orig_save:(function AttachmentInfo_save()
  {
    messenger.saveAttachment(this.contentType, this.url,
                             encodeURIComponent(this.name),
                             this.uri, this.isExternalAttachment);
  }), save:(function (save_dir) {

				lookout_lib.save_attachment( this, save_dir );

			}), parent:{contentType:"application/ms-tnef", name:"winmail.dat", uri:"imap-message://johndoe@mail.example.com/INBOX#AnotherUID", isExternalAttachment:false, size:25945, partID:"1.2", url:" imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat"}, part_id:3})
Lookout: Entering redraw_attachment_view()
LookOut:    Parent: [object Object]
            mMsgUri: imap-message://johndoe@mail.example.com/INBOX#AnotherUID
            requested Part_ID: 0
            Part_ID: 3
            Displayname: image001.jpg
            Content-Type: image/jpeg
            Length: 4702
            URL: 
            mimeurl: imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID?part=1.2&filename=winmail.dat.3
LookOut: onTnefData position 0  data.len 4702  outstrm null
LookOut: Entering onTnefEnd()
Lookout: Entering redraw_attachment_view()
LookOut: Entering onStopRequest()
LookOut: Removing winmail.dat
Lookout: Entering redraw_attachment_view()
Security Error: Content at imap://johndoe@mail.example.com:993/fetch%3EUID%3E.INBOX%someUID may not load or link to file:///C:%5CUsers%5C[removed for privacy]clip_image002.jpg.

**Comment by dugite-code** [comment]
The body_part_0.html is the stylized email text. I opened an issue about replacing the body with that yesterday, until then I feel it should remain.

Though I agree the vcf shouldn't show if it's empty. I'll look into that soon

**Comment by JaredRymer** [comment]
That sounds like a plan! Would you be able to put a reminder in here about a new beta? If one becomes available? 

I would contribute to fixing this... but that would just open a whole can of worms my end...

**Comment by dugite-code** [comment]
@JaredRymer [beta release v1.3.00b3](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.3.00b3) now skips empty vcf files. You'll be able to track my progress on the body_part_0.html in https://github.com/TB-throwback/LookOut-fix-version/issues/35

**Comment by JaredRymer** [comment]
Verified that it looks good on my end. Thanks for your help!

Would you consider turning on the _Remove Winmail.dat_ setting by default for the normies of the world?

**Comment by dugite-code** [comment]
It should be set to default remove as it is. I'll add it to my checklist to double check before I upload the release

**Comment by JannetGen** [comment]
It might be worth checking whether the issue is tied to a specific OS or app version. If it works on one version but not another, comparing the logs or error output between them could help pinpoint what changed. Also, a minimal reproduction would make the fix much easier to test.
