### ISSUE TITLE
incompatible with TB69 (beta)

### ISSUE THREAD

**Issue by n8v8R** [TB-throwback/LookOut-fix-version#38]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: W10 Pro x_64 v1903 b18362.267
* Thunderbird version number:  69.0b1 (64-bit)
* LookOut (fix version) version number: 1.3.01

# Current Behavior

![Annotation 2019-07-29 165313](https://user-images.githubusercontent.com/13611490/62060796-17d75480-b226-11e9-9e4f-618fe27eace3.png)

**Comment by dugite-code** [comment]
Please refer to https://github.com/TB-throwback/LookOut-fix-version/issues/30 Beta versions of Thunderbird are currently not supported due to significant changes in how extensions work. However I hope to be able to get it initial support in the coming months
