### ISSUE TITLE
TB 38.x + LookOutFix 1.3.01 not working

### ISSUE THREAD

**Issue by ManuelBorges** [TB-throwback/LookOut-fix-version#39]
I'm the person that posted on the addons page and led to this thread (auto?) https://github.com/TB-throwback/LookOut-fix-version/issues/37 but since the thread was closed I'm opening a new one since the issue is still here in the new version.

* Operating System: Ubuntu 16.04, Ubuntu 18.10, Windows 7, Windows 10
* Thunderbird version number: 38.6, 38.8
* 64 bit/32 bit: x86
* LookOut (fix version) version number: 1.3.00 and 1.3.01

# Expected Behavior
Either work as expected (like v1.2.x used to) or have "minVersion" updated to a version that works. Now we have 90 PCs with new version and reverting this manually will be a pain.

# Current Behavior
Email opens and we see the winmail.dat disappear but no attachments are then shown.
If revert to v1.2.x everything works as expected.

**Comment by dugite-code** [comment]
I've just re-tested 1.3.01 on a fresh Debian VM (64 bit) with 38.8 and had no issues.

Can you enable debugging in the add-on preferences and bring up the error console `ctrl+shift+j` and let me know if there are any error/warnings shown?

**Comment by ManuelBorges** [comment]
Hello!

Thanks for taking the time to look at this.
It seems version 1.2.25 recognizes the TNEF stream and version 1.3.01 does not.

Only error:
```
Timestamp: 30-07-2019 11:48:16
Error: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]
Source File: chrome://lookout/content/lookout.js
Line: 370
```

Made a vídeo here ( https://youtu.be/gH2rSPk5Qo4 ) with the debug opened.

Thanks.

**Comment by dugite-code** [comment]
Ok so looks like TB38 doesn't like how I was checking for the existence of the lightning calendar Please give the [Beta release v1.3.03b1](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.3.03b1) a try and see if this is the last of the errors.

**Comment by ManuelBorges** [comment]
Hello!

Beta release v1.3.03b1 work perfectly out of the box. No Errors and no Warnings!
Eagerly waiting to see it published. 

Thanks.
Best regards.

**Comment by dugite-code** [comment]
Release is uploaded to ATN awaiting approval
