### ISSUE TITLE
Can't remove winmail.dat attachment anymore

### ISSUE THREAD

**Issue by fkmediaworks** [TB-throwback/LookOut-fix-version#41]
Hi - running latest version on 2 separate Win10/64bit machines.

Since very recently, It's not possible to remove winmail.dat attachments anymore - previously, when selecting "remove all" (or however exactly it's called in English, I'm working on a German system), I was able to remove the whole winmail.dat attachment from the email. Now this doesn't work anymore. The options are there, but inactive.

Please fix, as atm I have to deactivate/restart, delete attachment, denn re-activate/restart again every time.

**Comment by dugite-code** [comment]
@fkmediaworks Please open the add-on options and uncheck the "Entfernen Sie Winmail.dat" option.

This was a feature that was added in Version 2.3.00 and hides the winmail.dat file from the attachments menu.

![image](https://user-images.githubusercontent.com/12742064/62746395-dc3c5600-ba81-11e9-9fb8-7ce04691da8e.png)

**Comment by dugite-code** [comment]
Ok after some tests I note the detach function is no longer working as expected even after disabling the Remove Winmail.dat option

**Comment by dugite-code** [comment]
@fkmediaworks Current work arround will be:

* Disable Hide Winmail.dat
* Save All attachments
* Detach Winmail.dat (right click winmail.dat detach)

I'm currently investigating a fix for the detach all button.

**Comment by dugite-code** [comment]
I've uploaded a beta [v1.3.04b1](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v1.3.04b1) that should fix your issues.

I still need to find a way to fix having to save the Winmail.dat file in a separate dialogue and test this in older versions of Thunderbird.

**Comment by fkmediaworks** [comment]
Thanks for helping - works good on my end now (though I didn't necessarily test various scenarios as you did).

**Comment by dugite-code** [comment]
Uploaded to ATN awaiting review
