### ISSUE TITLE
Full Lightning Integration

### ISSUE THREAD

**Issue by illtud** [TB-throwback/LookOut-fix-version#46]
* Operating System: Fedora Core 30 (linux)
* Thunderbird version number: 68.1 (cy_GB)
* 64 bit/32 bit: 64 bit
* LookOut (fix version) version number: 2.0.0

# Expected Behavior
An attached calendar invitation is presented as a button to accept/decline/tentative

# Current Behavior
Thunderbird recognises that there is an invitation, but does not present buttons. I get a message "This message contains an invitation to an event" but no options to act on the invitation, nor does it display information about the event (such as date/time/description).

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. receive email with invitation inside winmail.dat (.ics in this instance)
2. you get it...

**Comment by dugite-code** [comment]
This is the current expected behavior, you still need to double click the attached ics file.

I haven't finished figuring out how to properly integrate Lookout with Lightning. I decided flagging the event invite was a good stopgap

**Comment by alanorth** [comment]
I came here to ask the same thing. So we need to save the `.ics` file and then import it in the calendar. This is an unfortunate manual step, but not a huge issue for me because I don't have many meetings...

**Comment by dugite-code** [comment]
@alanorth Have a look at the `Open Calendaring Data directly` Lookout preference. This lets you double click the `.ics` file to add to lightning instead of downloading it.

This implementation just doesn't include the niceties like the add to calendar button.

**Comment by alanorth** [comment]
Thank you, @dugite-code. Where is the preference? I don't see it in add-ons or in Thunderbird preferences.

**Comment by dugite-code** [comment]
It's in the old Add-on Options dialogue. If you don't have the menu bar enabled press the alt key and it will pop up

![image](https://user-images.githubusercontent.com/12742064/111237125-5efa9f00-862f-11eb-97c0-d22e6c03bcb8.png)

**Comment by alanorth** [comment]
Ah! I never noticed that menu before. Works great. Thanks!

**Comment by illtud** [comment]
Thanks dugite!
