### ISSUE TITLE
"LookOut (fix version)" icon not showing in "Add-ons Manager"

### ISSUE THREAD

**Issue by ovari** [TB-throwback/LookOut-fix-version#47]
## Context

* Operating System: Windows 8.1
* Thunderbird version number: [68.1.2](https://www.thunderbird.net/en-US/thunderbird/68.1.2/releasenotes/)
* 64 bit/32 bit: 64-bit
* LookOut (fix version) version number: [2.0.0](https://addons.thunderbird.net/addon/lookout-fix-version/versions/2.0.0)

# Expected Behavior

LookOut (fix version) should display its icon in the Add-on Manager, as shown at [ATN](https://addons.thunderbird.net/addon/lookout-fix-version/), i.e.

![image](https://user-images.githubusercontent.com/17465872/67050206-bcad6200-f183-11e9-8457-445b7d195f21.png)

# Current Behavior

LookOut (fix version) displays a black jigsaw icon in the Add-on Manager

![LookOut icon missing](https://user-images.githubusercontent.com/17465872/67050141-92f43b00-f183-11e9-8720-8388f0d18a1b.png)

## Steps to Reproduce

Menu Bar > Tools > Add-ons > Extensions

Thank you

**Comment by ovari** [comment]
Please note that the icon for the "LookOut (fix version)" add-on does show correctly with:
* Operating System: [Linux Mint 19.2 Cinnamon](https://blog.linuxmint.com/?p=3786)
* Thunderbird version number: [60.9.0](https://www.thunderbird.net/en-US/thunderbird/60.9.0/releasenotes/)
* 64 bit/32 bit: 64-bit
* LookOut (fix version) version number: [1.3.04](https://addons.thunderbird.net/addon/lookout-fix-version/versions/1.3.04)

![image](https://user-images.githubusercontent.com/17465872/67050832-398d0b80-f185-11e9-82c8-df0da69624cc.png)

Thank you

**Comment by dugite-code** [comment]
Hummm, probably just a missing icon size. I'll have a look into the sizes other extensions are using.

**Comment by dugite-code** [comment]
Can you give the [v2.0.01b1](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v2.0.01b1) release a go. I added some icon related fixes to this release.

**Comment by ovari** [comment]
Thunderbird 68.2.2 is displaying the icon for LookOut 2.0.0 correctly.

LookOut 2.0.1b1 also displays the icon correctly with Thunderbird 68.2.2.

Sorry, we have not tested with Thunderbird 60.9.0.

Thank you
