### ISSUE TITLE
Displays [00] byte at the end of the file name

### ISSUE THREAD

**Issue by jorgk3** [TB-throwback/LookOut-fix-version#52]
## Context

Windows 10 64 bit, LookOut (fix version) 2.0.0, just installed.

## Issue

Displays [00] byte at the end of the file name, see screen shot:

![image](https://user-images.githubusercontent.com/8466558/72791119-11ef8880-3c37-11ea-9f68-0de6efbec27c.png)

I can provide the original message for testing, please contact me.

**Comment by dugite-code** [comment]
Interesting, the only time I've seen this before is when the winmail.dat was fully corrupted. Have you tried checking the option `Disable Filename Character Set Conversion`?

**Comment by jorgk3** [comment]
I have now (and restarted) and it makes no difference. The file is fine, double-clicking on the attachment opens it and the content is fine, too. Would you like it as test data? I believe I have your e-mail address.

**Comment by jorgk3** [comment]
I've sent you the test data, looks bad in the Sent mailbox as well.

**Comment by dugite-code** [comment]
Thanks, my initial test show there is nothing wrong with the data. Definitely a bug

**Comment by dugite-code** [comment]
In the debug logs there was a simple `.split("\0")[0]` hiding the issue. From my research it looks like this my be simply an artifact from JS TextDecoder not dealing with `\0` bytes and could be save to simply drop. However doing a Concatenate might be the go.
