### ISSUE TITLE
Only show file body_part_0.rtf

### ISSUE THREAD

**Issue by lnqminh** [TB-throwback/LookOut-fix-version#54]
* Operating System: Windows 7 & 8
* Thunderbird version number: 68.5
* 64 bit/32 bit: 64 bit
* LookOut (fix version) version number:  2.0.0

![Capture](https://user-images.githubusercontent.com/54611476/74704702-f4b4d680-5243-11ea-8deb-2b05ec7981dc.PNG)

Thanks

**Comment by dugite-code** [comment]
I'm sorry but I am unsure that you are asking for/about. Given that the total file size is only 16.5KB a single `.rtf` attachment is all I would expect and the winmail.dat file is hidden by default (this can be changed in the add-on preferences)

NOTE: This is the "Rich text format" copy of the text in the email

**Comment by lnqminh** [comment]
> I'm sorry but I am unsure that you are asking for/about. Given that the total file size is only 16.5KB a single `.rtf` attachment is all I would expect and the winmail.dat file is hidden by default (this can be changed in the add-on preferences)
> 
> NOTE: This is the "Rich text format" copy of the text in the email

When i disable Lookout, file size winmail.dat is 51.7 KB, and this attach have file .doc . those who are cc in this email are able to open the file attached

![Capture](https://user-images.githubusercontent.com/54611476/74708910-672bb380-5250-11ea-8b0c-50e382e48762.PNG)

**Comment by dugite-code** [comment]
There was a bug where the attachments pane isn't updated correctly. Try minimizing the panel and then opening it again.

I've also done a new [release today](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v2.0.01) that reverts to an old attachment method. See if that fixes your issue

**Comment by dugite-code** [comment]
Also please enbale debugging and check the error logs as [noted in the wiki](https://github.com/TB-throwback/LookOut-fix-version/wiki)

**Comment by lnqminh** [comment]
This error.

NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFile.create] lookout.js:371
    onTnefStart chrome://lookout/content/lookout.js:371
    tnef_file_notify chrome://lookout/content/tnef.js:528
    tnef_pack_parse_stream chrome://lookout/content/tnef.js:1912
    onDataAvailable chrome://lookout/content/lookout.js:343
LookOut: Entering onStopRequest()
LookOut: Removing winmail.dat
Lookout: Entering redraw_attachment_view()

**Comment by dugite-code** [comment]
This error should be covered in the 2.0.01 release. Please let me know if that fixes your issue
