### ISSUE TITLE
Cannot open attachments

### ISSUE THREAD

**Issue by El-Tacos** [TB-throwback/LookOut-fix-version#63]
* Operating System: W10 pro 64bits
* Thunderbird version number: 68.8
* 64 bit/32 bit: 64
* LookOut (fix version) version number: 2.0.3

[fr]
Bonjour,

Je ne sais pas depuis combien de temps ce problème existe puisque je reçois peu de mail expédiés via un outils Microsoft.

En ce moment tous les messages contenant un winmail.dat le contenu est visible avec l'affichage des bonne tailles de fichiers mais il est impossible de l'ouvrir par double clic ni de l'enregistrer sous.
Il n'a a aucune réaction ni de message d'erreur.

Merci.

trad [en]
Hello,

I don't know how long this problem has been around since I don't get many emails sent through a Microsoft tool.

At the moment all messages containing a winmail.dat the content is visible with the correct file sizes displayed but it is impossible to open it by double-clicking or save it as.
It has no reaction or error messages.

Thank you.

![image](https://user-images.githubusercontent.com/63443177/82290465-47b73a80-99a7-11ea-945e-5c7994da45f4.png)

**Comment by dugite-code** [comment]
1. Can you enable debugging and look at the logs? https://github.com/TB-throwback/LookOut-fix-version/wiki#enable-debugging
2. What options are enabled in the settings?
