### ISSUE TITLE
First attachment is missing

### ISSUE THREAD

**Issue by hcjehg** [TB-throwback/LookOut-fix-version#64]
* Operating System: Win 10 Pro 64 bit
* Thunderbird version number: 68.9.0 
* 64 bit/32 bit: TB 32 bit
* LookOut (fix version) version number: 2.0.3

# Expected Behavior

To see all attachments in winmail.dat in Thunderbird

# Current Behavior

It did not show the first attachment, in this case a pdf file.

## Steps to Reproduce

I only have one observation!

1. Send email from Outlook with several attachments to a thunderbird client
2. See that first attachment is not showing...

**Comment by dugite-code** [comment]
Please enable debugging and provide the logs [as described here](https://github.com/TB-throwback/LookOut-fix-version/wiki) additionally please disable the `Remove Winmail.dat` option to test the output.
