### ISSUE TITLE
Archive project if no New Maintainers found

### ISSUE THREAD

**Issue by dugite-code** [TB-throwback/LookOut-fix-version#65]
Due to changes coming in Thunderbird 78 and lack of time I am currently unable to actively maintain the project.

I still will be able to actively review pull requests when submitted so if you are interested in contributing please submit changes. Once I have someone actively contributing I will add them to the organization to allow them to perform administrative tasks.

**Comment by mhillct** [comment]
I've been meaning to learn to do this for a while now due to a number of add-ons in the same state and in order to implement something of my own for which I can find no add-on. If you could post any advice on getting up to speed, links to resources, etc. it would help me and other potential contributors.

**Comment by dugite-code** [comment]
It's great that you're willing to even look into helping any development. Currently this add-on and many others are stuck between being a Traditional XUL add-on and the modern MailExtension add-ons. Lookout for example is using the Wrapper API to make some of the old XUL code work in TB 78, it should be noted quite a bit of that code has already been [phased out of TB78](https://developer.thunderbird.net/add-ons/updating/tb68/changes#removed-xul-elements)

MailExtensions share the majority of the design choices with WebExtensions in Firefox so starting with [these docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons) is recommended. There is also [legacy docs](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Thunderbird_extensions) available for XUL extensions if you need to figure out what is going on there.

---

Main developer Hub page: https://developer.thunderbird.net/

* MailExtension docs: https://thunderbird-webextensions.readthedocs.io/
    * Pay special attention to the WebExperiments section as all the API's are not yet completed: https://thunderbird-webextensions.readthedocs.io/en/latest/how-to/experiments.html
* Thunderbird Github: https://github.com/thundernest
    * Wrapper API: https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis
* Mailing Lists: https://thunderbird.topicbox.com/
* Thunderbird core code search (Useful for low level interaction in MailExtension Experiments): https://searchfox.org

**Comment by dugite-code** [comment]
Unfortunately my company has switched back to Outlook from Thunderbird and so I now really only have my free time to do support.

What needs doing:

Continue porting to MailExtension. Thanks to John Bieling the plugin uses the Experiment wrapper API to add basic support for Thunderbird 78 however the plugin is broadly unchanged internally and needs to be converted to use the MailExtension API's.

- True lightning integration (this was a very hacky solution).

- Files cannot be drag and dropped from Thunderbird to the desktop.

- Decoded files are not used when forwarding an email message.

- The html body in modern TNEF emails isn't displayed and only shown as an attachment.

I know that proper integration for decoding TNEF emails was added to the roadmap for this year however it looks like this is being pushed back to TB 91+ https://developer.thunderbird.net/planning/roadmap-1#investigate-microsoft-tnef-support-tb-2022

Also see the Tracked bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=77811

I wish I was still able to use Thunderbird for my day to day work. Thank you to anyone who has provided help with this plugin and I look forward to someone taking this up in the future.

**Comment by dugite-code** [comment]
# This Project will become archived in 3 months from today if no new maintainers are found

**Comment by jobisoft** [comment]
I could take it (I am Thunderbird's add-on support engineer). What are the next steps?

**Comment by dugite-code** [comment]
@jobisoft I've added you as a maintainer to the project. I'll look into the ATN page permissions shortly, I think Oleksandr gave me permissions to add people there. If not I'm happy to continue doing the releases I just don't have the personal time for much coding these days.

As far as work needed to be done unfortunately I've only done some minor tweeks since implementing the Experiment wrapper API and as far as I understand it needs a complete port over to the mailextension. Last time I looked the messageId returned by messageDisplay wasn't the same as the ID used in [MessagePart](https://webextension-api.thunderbird.net/en/78/messages.html#messages-messagepart) However I don't see the note for that in the current docs.

_Theoretically_ the tnef.js should require no re-working to be used.

---

F.Y.I.  for anyone who is unfamiliar with the project, I am familiar with jobisoft and he contributed heavily to the work implementing the TB 78 Experiment wrapper API for lookout.

**Comment by jobisoft** [comment]
> ... and as far as I understand it needs a complete port over to the mailextension.

Experiments are still allowed, so we need to update the WindowListener API (which I [fixed](https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis/WindowListener) for TB91) and check a few [internal](https://developer.thunderbird.net/add-ons/updating/tb91/changes) changes. Once a working release is out, I will either focus on merging this into core (if it is accepted) or work on the WebExtension conversion.

> Last time I looked the messageId returned by messageDisplay wasn't the same as the ID used in MessagePart However I don't see the note for that in the current docs.

The WebExtension API is using unique IDs (not persistent across sessions), while two messages could have the same messageHeaderId. The messageHeaderId however is exposed since TB85 in the MessageHeader:
https://webextension-api.thunderbird.net/en/91/messages.html#messageheader

**Comment by jobisoft** [comment]
If someone wants to try the updated version:
https://github.com/TB-throwback/LookOut-fix-version/issues/74

**Comment by jobisoft** [comment]
I will do my best to keep this going, or to get it into core.
