### ISSUE TITLE
Cannot open winmail.dat.2 attachment

### ISSUE THREAD

**Issue by leeboontuck** [TB-throwback/LookOut-fix-version#66]
* Operating System: windows 10 home 64 bit 
* Thunderbird version number:68.10.0
* 64 bit/32 bit:32 bit
* LookOut (fix version) version number: 2.0.4

not able to open the attachment  . winmail.dat.2 

![Untitled](https://user-images.githubusercontent.com/42491359/87767396-2eb6f280-c84d-11ea-9c8d-fc86ef0c33ee.png)

**Comment by dugite-code** [comment]
Unfortunately these errors are not related to the Lookout add-on

As you say it's an attachment called winmail.dat.2 I presume this is either a forwarded email or the winmail.dat.2 was attached to a new email. If so the associated meta data with the file is missing so you have to ensure the option `Strict Content Type Matching` is disabled in preferences
