### ISSUE TITLE
Attachments from winmail.dat cannot be oppened.

### ISSUE THREAD

**Issue by virgoparna** [TB-throwback/LookOut-fix-version#69]
Thunderbird 78.4.0 32 bit
LookOut (fix version) 3.0.1
Windows 10 Pro ver 2004 64 bit

Attachment list shows list of attachments in winmail.dat (body_part_0.html, jpg files, actual attached files), but I cannot open/save them. On doubleclick on attachment error console shows:
Uncaught InternalError: too much recursion 
HandleMultipleAttachments chrome://lookout/content/lookout.js:947
HandleMultipleAttachments chrome://lookout/content/lookout.js:955
HandleMultipleAttachments chrome://lookout/content/lookout.js:955
.......
HandleMultipleAttachments chrome://lookout/content/lookout.js:955
lookout.js:947:22
[Learn more]

Same happens on right click and Save as...

But also, on just right click:
Uncaught InternalError: too much recursion
CanDetachAttachments chrome://openpgp/content/ui/enigmailMsgHdrViewOverlay.js:123
CanDetachAttachments chrome://openpgp/content/ui/enigmailMsgHdrViewOverlay.js:123
....
CanDetachAttachments chrome://openpgp/content/ui/enigmailMsgHdrViewOverlay.js:123
enigmailMsgHdrViewOverlay.js:123:1 
Although, that is probably a result of original problem.

**Comment by virgoparna** [comment]
Drag and drop from Thunderbird to file manager produces winmail.dat.N (N is probably some number of attachment in winmail.dat - the name matches link shown on mouse hover) file, that contains original winmail.dat file.

**Comment by dugite-code** [comment]
> Drag and drop from Thunderbird to file manager produces winmail.dat.N (N is probably some number of attachment in winmail.dat - the name matches link shown on mouse hover) file, that contains original winmail.dat file.

That is expected as drag and drop support was removed due to security and stability issues.

I have seen this error before but in that case it was a corrupted local copy of the email. If you are using IMAP try right clicking the storage folder, selecting properties and pressing the repair folder button.

**Comment by virgoparna** [comment]
Yes, repair folder fixed it even for local folder (I copied it from IMAP to local, when testing).

**Comment by mhillct** [comment]
I see only a winmail.dat attachment and nothing else on TB 78.4.0 and  Lookout (fix version) 3.0.1. It's as if Lookout is not present at all. Do you want this sample email with a winmail.dat attachment?

I don't have a lot of free time to work on this as a developer, but it's so important to get working right, I'll have to make some time.

**Comment by dugite-code** [comment]
@mhillct Lookout currently doesn't work if you are viewing the email in a separate window see #50 This is the most common issue for no conversions.

You can additionally try and disable the Strict Content Type Matching option in the Lookout options menu

If you wish to submit a winmail data sample you can send it through to the support email on the [ATN](https://addons.thunderbird.net/en-US/thunderbird/addon/lookout-fix-version/) page. If you continue having issues please open a separate issue

**Comment by mhillct** [comment]
That works, thanks for the quick response.

I'll have to consider if I can contribute to fixing #57

**Comment by dugite-code** [comment]
Ah I discovered this is indeed a bug after all. Should only present when updating. A simple re-start/folder repair was masking my reproduction of the issue
