### ISSUE TITLE
Does not work with Thunderbird 78.7.1

### ISSUE THREAD

**Issue by ERnsTL** [TB-throwback/LookOut-fix-version#72]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Thunderbird version number: 78.7.1
* 64 bit/32 bit: 64bit
* LookOut (fix version) version number: 306

# Expected Behavior

Instead of winmail.dat show the contained attachments

# Current Behavior

What is the current behavior? Not working since update to 78.7.1

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open a mail with winmail.dat attachment

**Comment by dugite-code** [comment]
Unfortunately I am unable to re-produce your issue and you have not provided enough details:

1. Please provide your operating system 
2. Please attach debug logs as [outlined here](https://github.com/TB-throwback/LookOut-fix-version/wiki#enable-debugging)

I know the issue template is currently missing this but do you have any other add-ons enabled? If so please list them.

Additionally disable any additional add-ons and re-enable one-by-one to eliminate them as a potential source of conflict.

**Comment by ERnsTL** [comment]
Greetings, it suddenly started working again after a week or so. Fixed :-)
