### ISSUE TITLE
Associated helper application does not exist

### ISSUE THREAD

**Issue by skaapman101** [TB-throwback/LookOut-fix-version#73]
Hi, can someone direct me to a tutorial? I get the following error message and can't open attachements: "***.pdf could not be opened, because the associated helper application does not exist. Change the association in your preferences."

Thank you.

Edit: Sorry, I forgot to say that I'm trying to open files contained inside a winmail.dat attachement.

**Comment by dugite-code** [comment]
This probably isn't an issue with Lookout. Double check your PDF software is associated within Thunderbird in the General section of the options menu. Additionally double check your operating system has the PDF software set to open PDF's by default

![image](https://user-images.githubusercontent.com/12742064/125881328-ff743962-041e-423e-8d26-20cf7aa9d9ab.png)

**Comment by skaapman101** [comment]
Thanks, I got it working, but for some reason I still get the same message when trying to open .rtf files. 

I set Notepad++ as the default program in Windows, and in the Thunderbird options, it doesn't matter which action I choose, I still get the same message. I tested opening an rtf attachment in a normal email (not inside winmail.dat) and it launches Notepad++ as it should. 

I'm still very grateful for LookOut, regardless of I can open rtf files, as they usually don't have any important information inside of them from the people who send me winmail.dat files. 

Thanks.

**Comment by dugite-code** [comment]
Sorry I can't reproduce your issue so most likely you have some other setting incorrectly set. I can open the `.rtf` files in word directly on my install. The `.rtf` files you are seeing are the email body text with the styling the sender used, we ignore this as the plain text version of the email is always included alongside this. Modern servers miss-configured to send winmail will have a `.html` file instead.
