### ISSUE TITLE
Incompatible with Thunderbird 91

### ISSUE THREAD

**Issue by dugite-code** [TB-throwback/LookOut-fix-version#74]

**Comment by jobisoft** [comment]
Version 3.0.7 for testing. Works for me. Feedback is appreciated.

[lookout_fix_version-beta-tb.zip](https://github.com/TB-throwback/LookOut-fix-version/files/7021039/lookout_fix_version-beta-tb.zip)

**Comment by belzebub40k** [comment]
@jobisoft I gave it a quick test and I would say it works 99%. I can save files but when I try to open the file it gets extracted to /tmp but nothing shows up. Opening "normal" attachemnts works fine. For example double clicking on the winmal.dat opens the regular "Opening..." Dialog. I'm using Thunderbird 91.0.1 on Debian 10 with KDE Plasma 5.14.5.

**Comment by jobisoft** [comment]
It only fails for some file types. rtf opens, jpg does not. What file types did you try?

**Comment by belzebub40k** [comment]
.html (body_part_0.html), .pdf, .png, .jpg.

**Comment by jobisoft** [comment]
Silent fail of `messenger.openAttachment`. Same parameters as in TB78. Bad.

**Comment by jobisoft** [comment]
How about 3.0.8?
[lookout_fix_version-beta-tb.zip](https://github.com/TB-throwback/LookOut-fix-version/files/7023449/lookout_fix_version-beta-tb.zip)

**Comment by belzebub40k** [comment]
Thanks, opening files works now but their is one other thing I notices. When double-clicking the files from the winmail.dat the attachment list collapses. Doing a double-click on a regular attachment this does not happen.

**Comment by dugite-code** [comment]
@belzebub40k is the option `Initially Show Attachment Pane` checked when you right click the top of the attachment pane?

There is a bit of a hacky workaround I had put in place to deal with the attachment pane blinking up and down as it added the attachments  that may be causing issues [L338](https://github.com/TB-throwback/LookOut-fix-version/blob/master/src/chrome/content/lookout.js#L338)

**Comment by belzebub40k** [comment]
Perfect, this solves the problem.

**Comment by dugite-code** [comment]
It shouldn't be opening the Pane if you don't have that checked, so It's still a bug really.

**Comment by jobisoft** [comment]
> When double-clicking the files from the winmail.dat the attachment list collapses. Doing a double-click on a regular attachment this does not happen.

It looks like this is happening in TB78 as well and has not been introduced by this update. We will take care of this (if possible) in a seperate issue.

**Comment by jobisoft** [comment]
@dugite-code : Wanna look over the PR? 
https://github.com/TB-throwback/LookOut-fix-version/pull/75

Can you push it to ATN?

**Comment by dugite-code** [comment]
The upload to ATN is done, should be available soon

@belzebub40k I've added your bug report here https://github.com/TB-throwback/LookOut-fix-version/issues/76
