### ISSUE TITLE
[Information] 4.3 validation failure

### ISSUE THREAD

**Issue by dugite-code** [TB-throwback/LookOut-fix-version#81]
I'm currently unable to upload v4.3 to ATN

`Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?`

I believe this is a bug in the addons-server and I am looking through that github to see if there are any valid existing issues.

**Comment by jobisoft** [comment]
I made a mistake. Can you change that to 95.0?
