### ISSUE TITLE
Lookout(+) urls

### ISSUE THREAD

**Issue by Rimole** [TB-throwback/LookOut-fix-version#82]
* LookOut (fix version) version number: 4.3

# Current Behavior

The "Details" tab at the add-on preferences as well as the About section at https://addons.thunderbird.net/en-gb/thunderbird/addon/lookout-fix-version/ give:
"Original LookOut add-on by Aron Rubin for Mozilla Thunderbird is abandoned September 30, 2011:
https://addons.mozilla.org/addon/lookout/
...
LookOut (fix version) - based on last version LookOut+ 1.2.15 by Attila K. Mergl (Last Updated: October 15, 2013)
https://addons.mozilla.org/addon/lookout-1/"

Both urls give just plain 404 messages. Current urls are:
https://addons.thunderbird.net/en-US/thunderbird/addon/lookout/
and
https://addons.thunderbird.net/en-US/thunderbird/addon/lookout-1/

Please update the given urls, thanks!

**Comment by dugite-code** [comment]
Done, Thanks for pointing that out
