### ISSUE TITLE
winmail.dat is no longer converted properly and the contents are no longer displayed as attachments

### ISSUE THREAD

**Issue by bierdosenhalter** [TB-throwback/LookOut-fix-version#85]
* Operating System: WIN 10 21H1
* Thunderbird version number: 91.5.1
* 64 bit/32 bit: 32-Bit
* LookOut (fix version) version number: 4.3

# Expected Behavior

contents of winmail.dat should be shown as separate files

# Current Behavior

winmail.dat is shown as a single attachment

**Comment by dugite-code** [comment]
@bierdosenhalter I've just tested on a 64bit install of 91.5.1 and haven't encountered any issues.

Could you enable debugging and check the console logs `Ctrl + Shift + J`. Then open a winmail.dat email in the same window (Not a new tab or a new window but in the message pane enabled via the message pane option in View -> Layout or by pressing `F81`)

Additionally with IMAP accounts it could (rarely) be an email not downloading correctly. Right clicking a folder selecting Properties and clicking the Repair Folder button will force a re-download of the whole folder.

**Comment by dugite-code** [comment]
Ah I just noticed that the options dialogue isn't showing in the menu. If you go to Preferences and click the "config editor" button at the bottom of the general section and search for lookout you will be able to manually set the debug option until that bug can be fixed

**Comment by nicrame** [comment]
11:09:51.387 1646129391387	addons.xpi	WARN	Checking C:\Program Files (x86)\Mozilla Thunderbird\distribution\extensions for addons
11:09:51.880 Ta strona jest w trybie zgodności wstecznej. Może to mieć wpływ na układ strony. „<!DOCTYPE html>” spowoduje użycie trybu standardowego.
[hiddenWindow.html](resource://gre-resources/hiddenWindow.html)
11:09:53.067 Successfully loaded OpenPGP library rnp.dll version 0.15.2+git20210806.dd923a4e.MZLA from C:\Program Files (x86)\Mozilla Thunderbird\rnp.dll [RNPLib.jsm:100:15](chrome://openpgp/content/modules/RNPLib.jsm)
11:09:53.117 Found 4 public keys and 4 secret keys (4 protected, 0 unprotected) [RNPLib.jsm:302:15](chrome://openpgp/content/modules/RNPLib.jsm)
11:09:53.118 Trying to load C:\Program Files (x86)\Mozilla Thunderbird\libotr.dll [OTRLib.jsm:64:11](resource:///modules/OTRLib.jsm)
11:09:53.119 Successfully loaded OTR library C:\Program Files (x86)\Mozilla Thunderbird\libotr.dll [OTRLib.jsm:72:13](resource:///modules/OTRLib.jsm)
11:09:53.130 services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource. [Utils.jsm:226](resource://services-settings/Utils.jsm)
11:09:53.345 NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED: JavaScript component does not have a method named: "getItems"'JavaScript component does not have a method named: "getItems"' when calling method: [calICalendar::getItems] [CalAlarmService.jsm:682](resource:///modules/CalAlarmService.jsm)
11:09:58.470 Ta strona jest w trybie zgodności wstecznej. Może to mieć wpływ na układ strony. „<!DOCTYPE html>” spowoduje użycie trybu standardowego.
[{e97c8106-d7ce-48c2-a7c8-fbbaec087af5}](moz-nullprincipal:{e97c8106-d7ce-48c2-a7c8-fbbaec087af5})
11:09:58.471 Ta strona jest w trybie zgodności wstecznej. Może to mieć wpływ na układ strony. „<!DOCTYPE html>” spowoduje użycie trybu standardowego.
[blank](about:blank)
11:09:58.495 Ta strona jest w trybie zgodności wstecznej. Może to mieć wpływ na układ strony. „<!DOCTYPE html>” spowoduje użycie trybu standardowego.
[fetch>UID>.INBOX>37331](imap://marcin%40marcinwilk%2Eeu@system.itos.pl:143/fetch%3EUID%3E.INBOX%3E37331)

And that is all inside debug Window.

**Comment by dugite-code** [comment]
There is a new release available and should be uploaded shortly. If you are still having these issues please let us know.

**Comment by jobisoft** [comment]
Could you check this version in TB 91? (Should also work in 102)
Does it resolve your issue?
[lookout_fix_version-beta-tb_5.2.zip](https://github.com/TB-throwback/LookOut-fix-version/files/8999633/lookout_fix_version-beta-tb_5.2.zip)

**Comment by jobisoft** [comment]
@dugite-code : Could you approve the PR and upload it to ATN?

**Comment by dugite-code** [comment]
@jobisoft done and done.
