### ISSUE TITLE
Strict Content Type Matching should be disabled

### ISSUE THREAD

**Issue by MatejKovacic** [TB-throwback/LookOut-fix-version#87]
## Context

* Operating System: Ubuntu 20.04.4 LTS
* Thunderbird version number: 91.9.1
* 64 bit/32 bit: 64 bit
* LookOut (fix version) version number: 4.3

# Expected Behavior
Should show PDF file instead of winmail.dat.

# Current Behavior
Shows only winmail.dat.

## Steps to Reproduce
1. click to e-mail
2. only winmail.dat attachment is shown

# Failure Information (for bugs)
<details>
<summary>Failure Logs</summary>

```
LookOut: debug enabled 
LookOut: Entering on_end_all_attachments()
LookOut: Entering scan_for_tnef()
LookOut: debug enabled 
LookOut: Entering on_end_all_attachments()
LookOut: Entering scan_for_tnef()
({message:({}), contentType:"", name:"winmail.dat", url:"imap://***@***:993/fetch%3EUID%3E/INBOX%3E220353?part=1.2&filename=winmail.dat", uri:"imap-message://***@***/INBOX#220353", isExternalAttachment:false, size:898347, sizeResolved:true, partID:"1.2"})
LookOut:    Content Type: ''
LookOut:    Strict Content check failed
```
</details>

## Solution

I found out that Strict Content Type Matching should be disabled. Would the solution be to have this disabled by default? Sorry to ask, but what is this setting anyway?

**Comment by dugite-code** [comment]
Strict Content Type Matching comes from Lookout's history of being a XUL plugin. Prior to the MailExtension migrations it was very probable for a plugin locking or even completely crashing the mail client. To avoid issues Lookout originaly only ever checked attachments correctly identified via the application\ms-tnef filetype. I added the ability to disable this behavior as when forwarded these attachments could loose this filetype identification, this lets Lookout open check each and every attachment in an email to see if it's a tnef file. As you can guess this is quite inefficient.

Lookout is still a legacy add-on and is not asynchronous, even though it's loaded via the Experiment wrapper API it's probably not something that should be changed at this time.

I had hoped the TNEF integration would be added directly into Thunderbird, but it looks like it has been removed from the roadmap. This is possibly as [jobisoft](https://github.com/jobisoft), Thunderbirds Add-on support engineer, is currently updating the add-on
