### ISSUE TITLE
strict_min_version  should be reverted to 91.0

### ISSUE THREAD

**Issue by olivluca** [TB-throwback/LookOut-fix-version#88]
commit 28d27951be0c02797d1bd3982a54872eac384464 breaks my automated deployment via policies.json, since the current version of thundebird is 91.10.0
I installed a locally modified xpi where strict_min_version is 91.0 and it works, so I think there is no need for it to be  102.0

**Comment by jobisoft** [comment]
It sounds like you deploy the wrong XPI or use the wrong path in your policy. Can I see it?

**Comment by olivluca** [comment]
I use the url for the latest version, so it's automatically updated
https://addons.thunderbird.net/firefox/downloads/latest/lookout-fix-version/latest.xpi

**Comment by olivluca** [comment]
I understand your concern but, before filing the bug, I tried the extension with thunderbird 91.10.0.
Anyway, I'll modify policies.json so it points at the old version, one more thing I'll have to worry about when I'll have to deploy 102 (which won't happen soon since it breaks other extensions I need).

**Comment by jobisoft** [comment]
I will think about modifying the min version and report back.

**Comment by olivluca** [comment]
Never mind, I already changed policies.json.

**Comment by jobisoft** [comment]
Could you test this version in 91 and 102?

[lookout_fix_version-beta-tb_5.2.zip](https://github.com/TB-throwback/LookOut-fix-version/files/8999625/lookout_fix_version-beta-tb_5.2.zip)

**Comment by olivluca** [comment]
It works in 91, I currently don't have a 102 to test
