### ISSUE TITLE
Thunderbird 104 compatibility

### ISSUE THREAD

**Issue by soriac** [TB-throwback/LookOut-fix-version#91]
- I am running the latest version
No, I can't run any version of the plugin. I am currently on Thunderbird 104.0b2 (64bit)
- I checked the documentation and found no answer
Yes
- I checked to make sure that this issue has not already been filed
Yes
- I have read the FAQ (https://github.com/TB-throwback/LookOut-fix-version/wiki/F.A.Q.)
Yes

## Context
* Operating System: Windows 10 64bit
* Thunderbird version number: 104.0b2
* 64 bit/32 bit: 64 bit
* LookOut (fix version) version number: N/A

# Expected Behavior
The plugin should run on this version of Thunderbird.

# Current Behavior
The plugin can't be installed on this version of Thunderbird.

## Steps to Reproduce
1. Install Thunderbird 104
2. Try to install the extension

## Comment
I was wondering if there's any instructions on how I would make a build by myself. I've never worked on thunderbird plugins, and when I worked on chrome/firefox plugins a few scripts were available. If there are any instructions on how to go about updating the plugin I could work on a pull request this weekend.

**Comment by soriac** [comment]
Oh, this is fantastic! Your suggestion works perfectly, I was able to install the extension and look at winmail.dat extensions without even restarting thunderbird.

It would still be great to have the updated version of the plugin on the official Thunderbird add-ons site, but as far as I'm concerned this issue can be closed.

**Comment by dugite-code** [comment]
I only increase max version only once the stable release is updated in case something gets changed in the interim. I'll leave this issue open for information for now.
