### ISSUE TITLE
LookOut Add-on does nothing

### ISSUE THREAD

**Issue by EscottHug** [TB-throwback/LookOut-fix-version#92]
My LookOut plugin is doing nothing on the winmail.dat I have.  As per the FAQ, this is because it's not a valid winmail.dat.  However other software are able to parse this winmail.dat, in particular the MailDroid app on my phone, and winmaildat.com.  There is a secret they have that LookOut does not.

* Operating System: Windows 10 Pro
* Thunderbird version number: 102.1.2
* 64 bit/32 bit: 32 bit
* LookOut (fix version) version number: 5.2

# Expected Behavior

winmail.dat contents displayed

# Current Behavior

winmail.dat is shown as an attachment that I can save or open.  The open option requires a program to parse it which I do not have.

# Failure Information (for bugs)

I attach this particular winmail.dat file for your viewing pleasure.
[winmail3.zip](https://github.com/TB-throwback/LookOut-fix-version/files/9337386/winmail3.zip)

**Comment by dugite-code** [comment]
@EscottHug I'm able to open this winmail.dat fine in TB 102.1.2 (64bit) by attaching to an email and disabling "strict content matching"

Was this a forwarded email? It's possible the content type was stripped, If so the preference "strict content matching" needs to be disabled to allow the plugin to perform the decoding.

**Comment by EscottHug** [comment]
Yes, that was it!!  By disabling Strict Content Matching, LookOut is able to parse this attachment.  Wondrous!  Thank you!  I didn't even know there were such things as Add-On preferences, so thanks also for that :)
